---
# System
timezone: US/Central

# Security
security_autoupdate_enabled: true
security_fail2ban_enabled: true

# Firewall
firewall_enabled: false

# OS Hardening
sysctl_overwrite:
  # Enable IPv4 traffic forwarding
  net.ipv4.ip_forward: 1

# Logs
remote_logs_enabled: true
remote_logs_server: logs.ghn.me
