dist: xenial
services: docker
env:
  - GIT_BRANCH="$TRAVIS_BRANCH" # Specify the branch name manually when on a detached HEAD
  - SC_VERSION='stable' # or "v0.4.7", or "latest"
jobs:
  include:
    - stage: "Tests"
      env:
        - DISTRIBUTION=ubuntu VERSION=bionic
        - DISTRIBUTION=ubuntu VERSION=xenial
        - DISTRIBUTION=ubuntu VERSION=trusty
      script: |
        wget "https://storage.googleapis.com/shellcheck/shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
        tar --xz -xvf "shellcheck-${SC_VERSION}.linux.x86_64.tar.xz"
        shellcheck() { "shellcheck-${SC_VERSION}/shellcheck" "$@"; }
        shellcheck --version
        sudo apt-get -qy update && sudo apt-get -qy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-ce
        docker --version
        find ./bin -type f -exec shellcheck {} +
        ./bin/run build
        ./bin/run test
    - stage: "Deploy"
      if: branch = master AND type != pull_request
      script: |
        pip install --user --upgrade ansible
        ansible --version
        ( echo "$ENCRYPT_KEY" | base64 --decode ) |  gpg --batch --yes --decrypt --passphrase-fd 0 --output ~/.ssh/deploy_rsa deploy_rsa.gpg && chmod 600 ~/.ssh/deploy_rsa
        ./bin/run deploy
notifications:
  webhooks:
    urls: https://vbot.ghn.me/travis
  slack:
    secure: dBW75rTN7tGVXX3oJfAoFRQyEgtZOZbE0NgV+DuKjCaAmPNGVXt0/csto8OpD9+g1KhW0wGxiK96OuN7hEB9y+VXg157nRo87AgbRthIXk/FbHIkogv7fFY6krwtA+M7P6461YOqaNgGV8mNDh2WOU3LjLa3GQoLlEWxNyEfUd0luqtTetFSzE9cNoJnS78/M59/btZ2+PwwOgdrDLlMey+ZxO/FB8LHjB16gllB+LO3RaXFhJLQNTbkenu4uZ6KnbQiVhJSek72A0g1IS5K2c1DPe5Gb8urJ+7FkINGjdt6sUOTiC4cHLHrG3JSUzap9j9V+1+597WvBkUXmGfDT7hMxd/8uJM5Qik1y5KeAGBk/thahaqXXuV4i8wO0unBZZIoZ9yu16/of92ysZXWb095O589SH+/ethiEUO/2AzEk+nhkdOKBtaIq3e7GhW6Os1l2Gip6bHNVrRCclf1JkBCPiPtnqESTvB4QMv3hTua1NC7wJlpFd8luvL9vYLvITmOAgzPxnOH+R3R20wT+YCZd6DC7b3e3RtlZkQ+BnUTvlzMdaVE4LMQegMgfQ6CXevV1F3hli/hyWagf4MHYFKLrqA0IUaCkVd56/+17/vWmS5iyvmnCg7LKObFxDojzwii1fxU94tlz8TSs/8C4FN2qeMkltcFpsIAOCOsW9c=
