---
- name: All hosts
  hosts: all
  become: yes
  gather_facts: false
  pre_tasks:
  - name: Install Python for Ansible
    raw: test -e /usr/bin/python || (sudo apt-get update && sudo apt-get -qy install python-minimal)
    changed_when: false
  - name: Provision Ansible user
    user:
      name: deploy
  - name: Provision Ansible user authorized keys
    authorized_key:
      user: deploy
      key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+4vPJ554LgwIZ7qK2DoipJe9U2yuRwUZpTtjJ4EHqASn+KUbWX8XA7ipwLloQiWO25U5S4UjAxy3jcd2ykkQWD2XeXnE9qZZTgRAJfOpTKNIlng7NBPg9gHJcUADU8EXTd52sYQRl67inQpExb9TnshAAmrShh2T2cVqzybLdHbukchEHRUgKINp/Ci/zPffhv7yWKz4EUzvZdisRVgd3tuHJotvrHk18OOhSaGGlcuiig2AQgpd4MV7+yyyYoT0keOPiRrf3OAAnFMzaQbaoekDvwRg8GmCY3oFZVzsxehB+jTGj1ICz60L8qTN2oeD6zOw1EQWOQldNw5TnTuUz deploy
      exclusive: yes
  - name: Add Ansible user to Sudoers
    lineinfile:
      path: /etc/sudoers.d/00_deploy
      line: 'deploy ALL=(ALL) NOPASSWD: ALL'
      state: present
      mode: 0440
      create: yes
      validate: 'visudo -cf %s'
  - name: Gathering Facts
    setup:

- import_playbook: playbooks/all.yml
- import_playbook: playbooks/vgh.yml
- import_playbook: playbooks/cosmin.yml
