---
- import_playbook: playbooks/all.yml
- import_playbook: playbooks/vgh.yml
- import_playbook: playbooks/cosmin.yml
- import_playbook: playbooks/docker_servers.yml
- import_playbook: playbooks/nfs_servers.yml
- import_playbook: playbooks/nfs_clients.yml
