---
# Python packages
pip_install_packages: [docker, jsondiff, pyyaml]

# OS Hardening
sysctl_overwrite:
  # Enable IPv4 traffic forwarding (for docker)
  net.ipv4.ip_forward: 1

# SSH Hardening
sftp_enabled: true
ssh_allow_tcp_forwarding: 'yes'

# Cron Jobs
cron_jobs:
  - name: Docker CleanUp
    minute: '2'
    hour: '2'
    job: docker system prune --force 2>&1 | /usr/bin/logger -t DockerCleanUp

# Security
security_autoupdate_enabled: true
security_fail2ban_enabled: true

# Enable swap on hosts.
swap_file_size_mb: '1024'
