---
# Admins
- name: Create Admins group
  group:
    name: admins
    system: yes
    state: present

- name: Add Admins to Sudoers
  lineinfile:
    path: /etc/sudoers.d/10_admins
    line: 'admins ALL=(ALL) NOPASSWD: ALL'
    state: present
    mode: 0440
    create: yes
    validate: 'visudo -cf %s'

# User accounts
- name: "Create user accounts"
  user:
    name: "{{ item.name }}"
    comment: "{{ item.comment | default(omit) }}"
    uid: "{{ item.uid | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    append: "{{ item.append | default(omit) }}"
    shell: "{{ item.shell | default(omit) }}"
  when: accounts is defined
  with_items: "{{ accounts }}"

- name: "Add authorized keys"
  authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_key }}"
  when: accounts is defined and item.authorized_key is defined
  with_items: "{{ accounts }}"

# Apt repositories
- name: Ensure Ubuntu universe repo is enabled ({{ ansible_distribution_version }} >= 16.04)
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
    state: present
  when: ansible_distribution_version >= '16.04'

- name: "Add extra APT repositories"
  apt_repository:
    repo: "{{ item.repo }}"
  with_items: "{{ apt_repositories }}"
  when: apt_repositories is defined
