---
# Security
security_autoupdate_enabled: true
security_fail2ban_enabled: true

# Enable swap on hosts.
swap_file_size_mb: '1024'

# OS Hardening
sysctl_overwrite:
  # Enable IPv4 traffic forwarding (for docker)
  net.ipv4.ip_forward: 1

# Docker
docker_users:
  - vlad
