---
- hosts: all
  become: yes
  roles:
    - common
    - geerlingguy.security
    - geerlingguy.ntp
    - geerlingguy.pip
    - role: cloudalchemy.node-exporter
      when: ansible_service_mgr is defined and ansible_service_mgr == 'systemd'
