---
- name: Common tasks on all nodes
  hosts: all
  become: yes
  pre_tasks:
    - name: Make sure Aptitude is installed
      package:
        name: aptitude
        state: present
      when: ansible_os_family == "Debian"
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - vladgh.common
    - geerlingguy.security
    - geerlingguy.firewall
    - geerlingguy.ntp
    - geerlingguy.pip

- name: Add GIT repositories on all hosts
  hosts: all
  become: yes
  tasks:
    - name: Ensure Git Package
      package:
        name: git
        state: present
    - name: Add VGS repository
      git:
        repo: https://github.com/vghn/vgs.git
        version: master
        dest: /opt/vgs
        force: yes
    - name: Add Vlad's Dotfiles
      git:
        repo: https://github.com/vladgh/dotfiles.git
        version: master
        dest: /opt/dotfiles
        force: yes
