---
- name: Common tasks on all nodes
  hosts: all
  become: yes
  pre_tasks:
    - name: Make sure Aptitude is installed
      package:
        name: aptitude
        state: present
      when: ansible_os_family == "Debian"
  roles:
    - role: geerlingguy.repo-epel
      when: ansible_os_family == "RedHat"
    - geerlingguy.ntp
    - geerlingguy.pip

- name: Vlad's Common Module
  hosts: all
  become: yes
  roles:
    - vladgh.common

- name: Add swap on hosts
  hosts: all
  become: yes
  vars:
    swap_file_size_mb: '1024'
  roles:
    - role: geerlingguy.swap
      when: swap_enable is defined and swap_enable
