---
- name: Ansible Control
  hosts: localhost
  connection: local
  become: yes
  gather_facts: false
  pre_tasks:
  - name: Ensure required packages are installed
    package:
      name:
        - sudo
        - git
        - python
        - python-pip
        - openssl
      state: present
  - name: Gathering Facts
    setup:
