---
- name: NFS server hosts
  hosts: nfs_servers
  become: yes
  roles:
    - geerlingguy.nfs

- name: Cosmin's NFS server hosts
  hosts: cosmin_nfs_servers
  become: yes
  tasks:
    - name: Create mountable dir
      file:
        path: /data
        state: directory
        owner: cmedia
        group: cmedia
