---
- name: NFS client hosts
  hosts: nfs_clients
  become: yes
  tasks:
    - name: Ensure NFS common is installed.
      apt:
        name: nfs-common
        state: present
        update_cache: yes

- name: Cosmin's NFS client hosts
  hosts: cosmin_nfs_clients
  become: yes
  tasks:
    - name: Create mountable dir
      file:
        path: /data
        state: directory
        owner: cmedia
        group: cmedia
    - name: Set mountpoints
      mount:
        name: /data
        src: "{{ hostvars['nebula']['ansible_default_ipv4']['address'] }}:/data"
        fstype: nfs
        opts: hard,rsize=1048576,wsize=1048576,timeo=600,retrans=2,_netdev
        dump: 0
        passno: 2
        state: mounted
