---
- hosts: vgh
  become: yes

  vars:
    pip_install_packages:
      - name: docker

  roles:
    - roles/common
    - geerlingguy.security
    - geerlingguy.ntp
    - geerlingguy.pip
    - geerlingguy.docker
