name: CI

on: [push]

jobs:
  build:
    env:
      VAULT_VERSION: '1.3.1'
      VAULT_ADDR: 'https://vault.ghn.me:8200'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Install dependencies
      run: python3 -m pip install --user --upgrade pip ansible hvac pycrypto
    - name: Install Vault
      run: |
            wget -q https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
            wget -qO - https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_SHA256SUMS | grep linux_amd64 | sha256sum -c
            unzip vault_${VAULT_VERSION}_linux_amd64.zip; sudo mv vault /usr/local/bin/
    - name: Authenticate Vault
      run: echo "::set-env name=VAULT_TOKEN::$(vault write -field=token auth/approle/login role_id=${{ secrets.VAULT_ROLE_ID }} secret_id=${{ secrets.VAULT_SECRET_ID }})"
    - name: Get deploy key
      run: vault kv get -field=id_rsa vgh/deploy > deploy_rsa && chmod 600 deploy_rsa
    - name: Download Ansible roles
      run: ansible-galaxy install --role-file requirements.yml
    - name: Run Ansible
      run: ansible-playbook site.yml
